# Generated by Django 4.2.5 on 2023-09-15 05:36

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Podcast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=1000, verbose_name="Title")),
                (
                    "description",
                    models.TextField(max_length=10000, verbose_name="Description"),
                ),
                (
                    "slug",
                    models.SlugField(
                        editable=False,
                        max_length=1000,
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="podcast_uploads",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["flac", "ogg", "mp3", "wav"]
                            )
                        ],
                        verbose_name="Podcast File",
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        upload_to="podcast_thumbnails", verbose_name="Podcast Thumbnail"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Author",
                    ),
                ),
            ],
        ),
    ]
